services:
  publicholidays.api:
    image: ${DOCKER_REGISTRY-}publicholidaysapi
    build:
      context: .
      dockerfile: PublicHolidays.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PublicHolidaysDb=Server=publicholidaysserver,1433;Database=PublicHolidaysDb;User Id=myadmin;Password=MyStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - app_network
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db
    restart: always
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "MyStrong!Passw0rd"
        ACCEPT_EULA: "myadmin"
    networks:
        - app_network
networks:
  app_network:
    driver: bridge
